export const mockPosts = [
  {
    id: 1,
    name: 'Albert Einstein',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 2,
    name: 'Issac Newton',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 1,
    like: 0,
    timestamp: '7 hours ago',
  },
  {
    id: 3,
    name: 'Galileo Galilei',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 4,
    name: 'Marie Curie',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 5,
    name: 'Michael Faraday',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 6,
    name: 'Stephen Hawking',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 7,
    name: 'Rosalind Franklin',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 8,
    name: 'Nikola Tesla',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 9,
    name: 'Ada Lovelace',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
];

export const blogPosts = [
  {
    id: 1,
    title: 'A Letter to all the Artists Building their Empires',
    subheader: 'Alex Bermudez August 15. 2023',
    image: './letter-to-artist.jpeg',
    summary:
      'I want you to know that your creative journey holds incredible potential. Building a business around your art on an ecommerce platform might seem like a daunting task, but remember, every masterpiece begins with a single brushstroke.',
    body: 'I want you to know that your creative journey holds incredible potential. Building a business around your art on an ecommerce platform might seem like a daunting task, but remember, every masterpiece begins with a single brushstroke.',
    url: 'http://127.0.0.1:5500/dist/08-15-2023-a-letter-to-all-the-artists-building-their-empires.html',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 2,
    title: 'Best Ecommerce Platform for Artists in 2023',
    subheader: 'Alex Bermudez August 15. 2023',
    image: './ecommerce-art.jpeg',
    summary:
      'Embark on an artistic journey into ecommerce platforms. Unleash your creativity and tap into the lucrative world of online business. Unlock new horizons and let your unique vision merge seamlessly with the digital marketplace.',
    body: 'I want you to know that your creative journey holds incredible potential. Building a business around your art on an ecommerce platform might seem like a daunting task, but remember, every masterpiece begins with a single brushstroke.',
    url: 'http://127.0.0.1:5500/dist/08-13-2023-best-ecommerce-platform-for-artists-in-2023.html',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
];

export const communityPosts = [
  {
    id: 1,
    title: 'Albert Einstein',
    subheader: 'test',
    summary: 'test',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 2,
    title: 'Issac Newton',
    subheader: 'test',
    summary: 'test',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 1,
    like: 0,
    timestamp: '7 hours ago',
  },
  {
    id: 3,
    title: 'Galileo Galilei',
    subheader: 'test',
    summary: 'test',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 4,
    title: 'Marie Curie',
    subheader: 'test',
    summary: 'test',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 5,
    title: 'Michael Faraday',
    subheader: 'test',
    summary: 'test',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 6,
    title: 'Stephen Hawking',
    subheader: 'test',
    summary: 'test',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 7,
    title: 'Rosalind Franklin',
    subheader: 'test',
    summary: 'test',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 8,
    title: 'Nikola Tesla',
    subheader: 'test',
    summary: 'test',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 9,
    title: 'Ada Lovelace',
    subheader: 'test',
    summary: 'test',
    body: 'This impressive paella is a perfect party dish and a fun meal to cook together with your guests. Add 1 cup of frozen peas along with the mussels, if you like.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
];

export const yourJamSessions = [
  {
    id: 0,
    name: 'Your One Active Sesh',
    body: 'You are allowed one concurrent session at a time.',
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
];

export const yourSessionInvites = [
  {
    id: 0,
    name: 'Demo Sesh Invite',
    body: "If you are invited to an active Jam Sesh, you'll get a pop-up notification, and it will show up here.",
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 1,
    name: 'Demo Sesh Invite 2',
    body: "If you are invited to an active Jam Sesh, you'll get a pop-up notification, and it will show up here.",
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
];

export const activeJamSessions = [
  {
    id: 0,
    name: 'The Frijoleos',
    body: "Good old fashion corridos. Come on in, hang out, and if you'd like, we take requests from the audience.",
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
  {
    id: 1,
    name: 'MWA: Mexicans With Attitudes',
    body: "Good old fashion corridos. Come on in, hang out, and if you'd like, we take requests from the audience.",
    comments: 18,
    like: 3,
    timestamp: '7 hours ago',
  },
];
